### ISSUE TITLE
React jsx syntax support

### ISSUE THREAD

**Issue by pmizio** [b3nj5m1n/kommentary#11]
React files use two types of comments depending on context:
https://reactjs.org/docs/faq-build.html#how-can-i-write-comments-in-jsx

```javascript
// const test = 'This is standard js comment'

const Example = () => {
  return (
    <div>
      <h1>Test</h1>
      {/* <p>This is jsx comment</h1> */}
    </div>
  )
}
```

**Comment by b3nj5m1n** [comment]
Hi. This has been discussed on Reddit as well, I'm really sorry to say this, but I think this is outside the scope of this plugin.

The problem here is, as you mentioned, the type of comment that needs to be used depends on the context, I think adding the logic for context-awareness would be inappropriate for this plugin.

You can take a look at [context-commentstring](https://github.com/suy/vim-context-commentstring/blob/master/plugin/context-commentstring.vim), which sets the commentstring depending on context (And commentstring can be used by this plugin), however when I tried it, it didn't work for jsx/tsx (Although it did work for html & script tags). That project also seems to have been abandoned.

Perhaps we could look into making a new plugin which replaces context-commentstring or look for the existing problems with it, but I won't work on implementing this here. That being said, I'd definitely consider pull requests.

For the time being, you can probably work around this with different mappings, for example gc comments out using //, gC comments out using {/* */}, although to make that a viable option the code for this plugin needs to be refactored a bit (I am actively working on that though).

If the above sounds like an acceptable option to you, leave a comment, and I'll write out an example config as soon as that is properly supported.

**Comment by pmizio** [comment]
Maybe if I find some time I try to write extension for context awareness. But for that time separate keybinding is also acceptable so when You finish refactor any info about how configure this additional keybinding would be awesome :)

**Comment by b3nj5m1n** [comment]
@pmizio Alright, that wasn't as bad as I had anticipated. 

![Peek 2021-02-02 23-32](https://user-images.githubusercontent.com/47924309/106671584-a3157100-65a6-11eb-8787-a9067de1c40b.gif)

You can do this pretty elegantly now (Because of b84cc58381a4bfb34d94d01160fa39dfd623e945 and 0dc6887e2c5c9c4c4eded4885590f0c25933515d), here is what you would put in your init.lua:
```lua
--[[ This is our custom function for toggling comments with a custom commentstring,
it's based on the default toggle_comment, but before calling the function for
toggling ranges, it sets the commenstring to something else. After it is done,
it sets it back to what it was before. ]]
function toggle_comment_custom_commentstring(...)
    local args = {...}
    -- Save the current value of commentstring so we can restore it later
    local commentstring = vim.bo.commentstring
    -- Set the commentstring for the current buffer to something new
    vim.bo.commentstring =  "{/*%s*/}"
    --[[ Call the function for toggling comments, which will resolve the config
    to the new commentstring and proceed with that. ]]
    require('kommentary.kommentary').toggle_comment_range(args[1], args[2],
        require('kommentary.config').get_modes().normal)
    -- Restore the original value of commentstring
    vim.api.nvim_buf_set_option(0, "commentstring", commentstring)
end
```
And then, the admittedly less elegant, mappings:
```lua
-- Set the extra mapping for toggling a single line in normal mode
vim.api.nvim_set_keymap('n', 'gCC',
'<cmd>lua require("kommentary");kommentary.go(' .. require('kommentary.config').context.line .. ', '
.. "'toggle_comment_custom_commentstring'" .. ')<cr>',
{ noremap = true, silent = true })
-- Set the extra mapping for toggling a range with a motion
vim.api.nvim_set_keymap('n', 'gC',
'v:lua.kommentary.go(' .. require('kommentary.config').context.init .. ', ' ..
"'toggle_comment_custom_commentstring'" .. ')',
{ noremap = true, expr = true })
-- Set the extra mapping for toggling a range with a visual selection
vim.api.nvim_set_keymap('v', 'gC',
'<cmd>lua require("kommentary");kommentary.go(' .. require('kommentary.config').context.visual .. ', '
.. "'toggle_comment_custom_commentstring'" .. ')<cr>',
{ noremap = true, silent = true })
```
*Note that this will only work if you have the language configured to use vim's commentstring, see 0dc6887e2c5c9c4c4eded4885590f0c25933515d.*
