### ISSUE TITLE
New Feature: Skip Creation of Default Mappings

### ISSUE THREAD

**Issue by gblock0** [b3nj5m1n/kommentary#17]
My thought is to add a setting like `vim.g.KCreatDefaultMappings` which defaults to `1`. If it is `0` then Kommentary would skip creating the default mappings.

I'm happy to take a swing at creating this feature if you're open to it!

**Comment by b3nj5m1n** [comment]
Hi, that's one of the few features I still want to add, so I definitely think it's a good idea!

> I'm happy to take a swing at creating this feature if you're open to it!

That would be great! It shouldn't be too hard to implement, I would suggest that we move the call to `use_default_mappings` into the `setup` function instead of the plugin file, then we can check for the state of a variable like the `KCreatDefaultMappings` you suggested in the setup function.

I'd be awesome if you make a PR for this, otherwise I'll probably implement it myself tomorrow. One more thing, if you end up making a PR, please name the variable `kommentary_create_default_mappings` (A little bit more verbose and in snake_case, I know it's a little thing but I try to keep the code style as consistent as possible :) ).

**Comment by gblock0** [comment]
I'll take a swing at it tonight.

> That would be great! It shouldn't be too hard to implement, I would suggest that we move the call to `use_default_mappings` into the `setup` function instead of the plugin file, then we can check for the state of a variable like the `KCreatDefaultMappings` you suggested in the setup function.

Sounds good!

> I'd be awesome if you make a PR for this, otherwise I'll probably implement it myself tomorrow. One more thing, if you end up making a PR, please name the variable `kommentary_create_default_mappings`

No problemt! Totally makes sense!

**Comment by b3nj5m1n** [comment]
Implemented with #19.
