### ISSUE TITLE
Issues with block line comments in lua

### ISSUE THREAD

**Issue by kristijanhusak** [b3nj5m1n/kommentary#3]
Hi,

I was giving block commenting  a try, and ran into one issue. Here's the gif:

![kommentary-issue](https://user-images.githubusercontent.com/1782860/106393919-06ae6b80-63fa-11eb-81a7-d7970056c87b.gif)

I'm not sure how this should be handled though.

Also, did you thought about adding the block comment style like vim-commentary does, where each line gets the single line comment?

**Comment by b3nj5m1n** [comment]
Hi, this isn't an issue with this plugin, it's just the way comments are handled in lua.

You're trying to comment in a section which contains `]]`, meaning as far as lua is concerned, the comment ends there. As you can see, the plugin correctly adds the prefix at the end, it just doesn't have the desired effect.

> I'm not sure how this should be handled though.

I'm also not sure how this should be handled, a possibility would be checking for illegal patterns in a string before block commenting it in, but since that does add a bit of complexity to the code (The whole text being commented in has to be checked every time, image you want to comment in a file with tens of thousands of lines of code) I haven't added it yet, and I'm not sure if I will.

> Also, did you thought about adding the block comment style like vim-commentary does, where each line gets the single line comment?

Yes! You can already do that, it's just hidden behind a bit of configuration. Here are your (current) options:

### Define a function and map to it

The drawback here is that you need to essentially rewrite the parts of the `toggle_comment` function (In the init file), but here it is for *just visual*:

Put this in your `init.lua` if you have one, or in our `init.vim` in an EOF lua block:
```lua
function comment_in_selection_singles()
    local kommentary = require('kommentary.kommentary')
    local config = require('kommentary.config')
    local line_number_start = vim.fn.getpos('v')[2]
    local line_number_end = vim.fn.getcurpos()[2]
    kommentary.toggle_comment_range(line_number_start, line_number_end, config.get_modes().force_single)
end
```
The crucial part here is setting the mode to `force_single`, which will force the function to comment in every line using single-line comment style. You could also set it to `force_multi`, which would force the function to use a multi-line comment style, even when you're only commenting out a single line.

Then you can map to it:
```vim
vnoremap gc <cmd>lua comment_in_selection_singles()<cr>
```

### Remove the option for multi-line comments

The drawback here is that you will lose the ability to do multi-line comments in that language completely, but that may not be a problem. Put this in your `init.lua`:
```lua
require('kommentary.config').config["lua"] = {"--", false}
```
That will overwrite the default config for the lua filetype and tell the plugin that the language doesn't support multi-line comments.

**Comment by kristijanhusak** [comment]
Thanks for the explanation. I think it would be great to have a mapping that does multi line single comment out of the box (The function you wrote above).Something like `gcC` or something like that, just to be able to handle these edge cases more easily. 
I'm pretty sure current block line implementation covers 99% of the cases, but edge cases like this happen. I can also see it happen in html, since it has weird comment strings.

**Comment by b3nj5m1n** [comment]
> I think it would be great to have a mapping that does multi line single comment out of the box

I agree, I'm just not quite sure how to implement it elegantly.

> (The function you wrote above)

As I said, the problem with this function is the repetition of code, ideally we would have a function which is called by mappings, this would then figure out in which mode to operate and on which line/range, then call a second function with those things as arguments, and that second function could be given as an argument to the first function, I think this would allow for easy and elegant configuration. I just haven't gotten around to implementing this yet, since up to now my main focus was making sure that the features that do exist work correctly.

I'll probably implement this soon, I might write the rest of the unit tests first though. If you're interested in giving it a go yourself, I'm always open to PRs.

**Comment by kristijanhusak** [comment]
Ok, thanks. I can give it a try, but since you have an idea how to make this easily configurable, I'll just leave it to you. I believe you'll do it much better.

**Comment by b3nj5m1n** [comment]
Alright, I have implemented basic support for this, for now this not work when using on motions, but a mapping for visual mode is built-in. (I might implement a bit of a workaround to get it to work with motions)

I'm not going to merge this into main now, since I really, really need to sleep and don't trust my ability to judge this code right now, so I'd be very grateful if you could take this for a test drive and tell me if you experience any issues.

Here is the branch: [go-callback](https://github.com/b3nj5m1n/kommentary/tree/go-callback)

If you install from that branch, the mapping in visual mode should be with the new functionality by default, so you shouldn't have to do anything, when you try to comment out a single line with gcc it will work normally, the same goes for gc-motion, but if you do gc on a selection it should comment it in using only single-line comments.

**Comment by kristijanhusak** [comment]
I gave it a try, looks like it's working fine. I tried it in a bigger JS file (> 1k LOC), and it can be a bit slow (with foldmethod=syntax). Tpope's commentary have same issue, and here are few pending PRs that resolve that issue:

https://github.com/tpope/vim-commentary/pull/136
https://github.com/tpope/vim-commentary/issues/110#issuecomment-511793483

Both of these solutions works, so you just have to pick the one that works better for you.

Having blocks commented in the way you initially implemented does not cause this issue, so that is a plus.

**Comment by b3nj5m1n** [comment]
It's great to hear that this is working, I also tried it out a bit and had no issues (But I also did try it on big files).

The way it's implemented right now, we just loop over the range of lines, then call the commenting in function for a single line on each line individually. If we just change that, we can set the whole range in one go, which means foldmethod shouldn't be affected, also this would make it possible to set an indentation level for the whole range (Atm, when you comment in a range that with different indentation levels, each line will be commented in at the first non-whitespace character, maybe we should search for the lowest level of indentation in the range and comment in everything at that index, although this should probably be an option).

If you want to give this a go, (It shouldn't be too complicated, the function we're after is called `comment_in_range_single` in kommentary.lua) I'd be very grateful, since I have some school work to do right now, if you don't want to I can probably get on this myself later. (If you do decide to give it a go, make your changes against the go-callback branch as well)

Thanks for bringing this to my attention!

**Comment by kristijanhusak** [comment]
There's no rush on this :) It's really an edge case where we need this. I'll let you slowly adapt it and set it up however you want. I just reported it since i ran into it.

**Comment by b3nj5m1n** [comment]
Maybe we should close this issue, since the original issue has been addressed?

If you feel that this issue has been answered, please close it, I'll open two new ones, one for tracking the performance issue and one for proper configuration (Configure which comment style to use by default on a per-filetype basis, configure the indentation of single-comment ranges, etc.).

**Comment by kristijanhusak** [comment]
Yeah, i'll close it. Thanks.
