### ISSUE TITLE
Feature Request - Allow to configure a hook function run before command

### ISSUE THREAD

**Issue by weilbith** [b3nj5m1n/kommentary#43]
Hey, 
I was just about to integrate this with the [nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring) plugin. In short it updates the `commentstring` option based on the current cursor location using Treesitter. Per default it runs on the `CursorHold` event, which I think is not necessary/too often. I would rather have it run just each time before I want to do a comment.
I could now write my own custom stuff to make this happen. But actually I would love to just have your mappings, but have a configuration options like:

```lua
require('kommentary.config').configure_language("default", {
    pre_comment_hook = require('ts_context_commentstring.internal').update_commentstring(),
})
```

Do you think it would be a feature you are willed to add? 🤔

**Comment by b3nj5m1n** [comment]
Hi, this sounds like a good idea, I don't have too much time on my hands at the moment, so it might be a while until I can implement it.

In the meantime, pull request are very much appreciated.

**Comment by b3nj5m1n** [comment]
This implementation runs the hook function before returning the config table, this unfortunately means that it'll be run 3 times per commenting because the get config function is called multiple times. I might look into how to reduce that number later, until then pull requests are welcome as always.

Here's a rough example:
```lua
require("kommentary.config").configure_language("lua", {
    hook_function = function()
       vim.api.nvim_buf_set_option(0, 'commentstring', '{%s}')
    end,
    single_line_comment_string = "auto",
    multi_line_comment_strings = "auto"
})
```

The hook function will set the commentstring to something arbitrary, single_line and multi_line_comment_strings are both configured to use the commentstring provided by vim instead of from the config table.

Let me know if this is a satisfactory implementation, and sorry it took so long.

**Comment by weilbith** [comment]
Amazing. Thank you very much! 🙏🏾

**Comment by clason** [comment]
Sorry for the drive-by comment on an old issue, but that was exactly what I was going for in #45 (dynamically looking up the current comment string rather than relying on something else needlessly updating a variable in the background).

Might I suggest mentioning this in the README (under "Advanced Config")? I'm sure there are _a lot_ of people who'd be very interested in learning about this functionality.
