### ISSUE TITLE
Tree-sitter support for injected languages

### ISSUE THREAD

**Issue by clason** [b3nj5m1n/kommentary#45]
One thing that tree-sitter for neovim allows is language injection: you can declare regions as different languages (code snippets in markdown, Lua heredoc in vimscript (not yet), C in Lua for FFI, ...), which is then parsed and highlighted by the corresponding parser (and queries).

Kommentary could make use of this to dynamically get the correct comment strings for the current region (if tree-sitter is running for the buffer) by checking the language using the code snippet in https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/3#issuecomment-820360620 .

**Comment by b3nj5m1n** [comment]
Why would you not just use that plugin?

**Comment by clason** [comment]
Because I already use your plugin and don't want to have two if it's not necessary? (By the same token, why would I then use your plugin and not tpope/vim-commentary?)

But it's only a suggestion; I thought it would be a) useful for kommentary to support multiple (injected) languages in one buffer (as this is a feature I've seen requested before) and b) relatively easy to implement. If you don't think so, feel free to close this issue.

**Comment by b3nj5m1n** [comment]
Well the plugin you linked is supposed to be used with a seperate commenting plugin, like tpopes or mine.

This might not be too difficult to implement initially, but it adds another thing to maintain, and something that might very well change in the future, since treesitter is still fairly new. (The nvim integration, not treesitter itself)

I think it makes more sense to handle these two things independently with seperate plugins, it also means greater flexibility since other plugins that aren't necessarily for commenting can make use of the treesitter functionality.

Still, thank you for the suggestion. Perhaps we should add a few lines to the readme about how to integrate that plugin with kommentary.

**Comment by ram02z** [comment]
I am trying to use this plugin in conjuction with the mentioned plugin (nvim-ts-commentary). However, I cannot get it to work, am I missing a step?

**Comment by b3nj5m1n** [comment]
@ram02z  Haven't tried using it myself yet, are you setting the comment string to auto and triggering the other plugin to update when necessary?

**Comment by ram02z** [comment]
Sorry, it does actually work. I lowered my updatetime to 100 and it works fine.
